// source: api/v1alpha1/classifier/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var localGlobalThis = require("../../../global.js");
var proto = localGlobalThis.proto;
var goog = jspb;
var global = localGlobalThis || 
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var api_v1alpha1_classifier_entities_pb = require('../../../api/v1alpha1/classifier/entities_pb.js');
goog.object.extend(proto, api_v1alpha1_classifier_entities_pb);
goog.exportSymbol('proto.api.v1alpha1.classifier.DeleteFileTemplateRequest', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.DeleteFileTemplateResponse', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.GetFileTemplateRequest', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.GetFileTemplateResponse', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ListFileTemplatesRequest', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ListFileTemplatesResponse', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ParseFileRequest', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ParseFileRequest.OptCase', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.ParseFileResponse', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.UpdateFileTemplateRequest', null, global);
goog.exportSymbol('proto.api.v1alpha1.classifier.UpdateFileTemplateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ParseFileRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_);
};
goog.inherits(proto.api.v1alpha1.classifier.ParseFileRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ParseFileRequest.displayName = 'proto.api.v1alpha1.classifier.ParseFileRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.displayName = 'proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.displayName = 'proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ParseFileResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.ParseFileResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ParseFileResponse.displayName = 'proto.api.v1alpha1.classifier.ParseFileResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.UpdateFileTemplateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.displayName = 'proto.api.v1alpha1.classifier.UpdateFileTemplateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.UpdateFileTemplateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.displayName = 'proto.api.v1alpha1.classifier.UpdateFileTemplateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.DeleteFileTemplateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.displayName = 'proto.api.v1alpha1.classifier.DeleteFileTemplateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.DeleteFileTemplateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.displayName = 'proto.api.v1alpha1.classifier.DeleteFileTemplateResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.ListFileTemplatesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ListFileTemplatesRequest.displayName = 'proto.api.v1alpha1.classifier.ListFileTemplatesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.v1alpha1.classifier.ListFileTemplatesResponse.repeatedFields_, null);
};
goog.inherits(proto.api.v1alpha1.classifier.ListFileTemplatesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.ListFileTemplatesResponse.displayName = 'proto.api.v1alpha1.classifier.ListFileTemplatesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.GetFileTemplateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.GetFileTemplateRequest.displayName = 'proto.api.v1alpha1.classifier.GetFileTemplateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.classifier.GetFileTemplateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.classifier.GetFileTemplateResponse.displayName = 'proto.api.v1alpha1.classifier.GetFileTemplateResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_ = [[3,4,6]];

/**
 * @enum {number}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.OptCase = {
  OPT_NOT_SET: 0,
  RAW_DATA: 3,
  REPARSE_FILE: 4,
  PARSE_WITH_HINTS: 6
};

/**
 * @return {proto.api.v1alpha1.classifier.ParseFileRequest.OptCase}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getOptCase = function() {
  return /** @type {proto.api.v1alpha1.classifier.ParseFileRequest.OptCase} */(jspb.Message.computeOneofCase(this, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ParseFileRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    rawData: msg.getRawData_asB64(),
    reparseFile: (f = msg.getReparseFile()) && proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.toObject(includeInstance, f),
    parseWithHints: (f = msg.getParseWithHints()) && proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ParseFileRequest;
  return proto.api.v1alpha1.classifier.ParseFileRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawData(value);
      break;
    case 4:
      var value = new proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile;
      reader.readMessage(value,proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.deserializeBinaryFromReader);
      msg.setReparseFile(value);
      break;
    case 6:
      var value = new proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints;
      reader.readMessage(value,proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.deserializeBinaryFromReader);
      msg.setParseWithHints(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ParseFileRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getReparseFile();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.serializeBinaryToWriter
    );
  }
  f = message.getParseWithHints();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplateId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    hints: (f = msg.getHints()) && api_v1alpha1_classifier_entities_pb.ParseHints.toObject(includeInstance, f),
    renameFieldsMap: (f = msg.getRenameFieldsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile;
  return proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFileTemplateId(value);
      break;
    case 2:
      var value = new api_v1alpha1_classifier_entities_pb.ParseHints;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.ParseHints.deserializeBinaryFromReader);
      msg.setHints(value);
      break;
    case 6:
      var value = msg.getRenameFieldsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplateId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getHints();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      api_v1alpha1_classifier_entities_pb.ParseHints.serializeBinaryToWriter
    );
  }
  f = message.getRenameFieldsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional int64 file_template_id = 1;
 * @return {number}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.getFileTemplateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.setFileTemplateId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional ParseHints hints = 2;
 * @return {?proto.api.v1alpha1.classifier.ParseHints}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.getHints = function() {
  return /** @type{?proto.api.v1alpha1.classifier.ParseHints} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_classifier_entities_pb.ParseHints, 2));
};


/**
 * @param {?proto.api.v1alpha1.classifier.ParseHints|undefined} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} returns this
*/
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.setHints = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.clearHints = function() {
  return this.setHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.hasHints = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * map<string, string> rename_fields = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.getRenameFieldsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile.prototype.clearRenameFieldsMap = function() {
  this.getRenameFieldsMap().clear();
  return this;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.toObject = function(includeInstance, msg) {
  var f, obj = {
    rawData: msg.getRawData_asB64(),
    hints: (f = msg.getHints()) && api_v1alpha1_classifier_entities_pb.ParseHints.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints;
  return proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 7:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRawData(value);
      break;
    case 8:
      var value = new api_v1alpha1_classifier_entities_pb.ParseHints;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.ParseHints.deserializeBinaryFromReader);
      msg.setHints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRawData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      7,
      f
    );
  }
  f = message.getHints();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      api_v1alpha1_classifier_entities_pb.ParseHints.serializeBinaryToWriter
    );
  }
};


/**
 * optional bytes raw_data = 7;
 * @return {string}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.getRawData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * optional bytes raw_data = 7;
 * This is a type-conversion wrapper around `getRawData()`
 * @return {string}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.getRawData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawData()));
};


/**
 * optional bytes raw_data = 7;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawData()`
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.getRawData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.setRawData = function(value) {
  return jspb.Message.setProto3BytesField(this, 7, value);
};


/**
 * optional ParseHints hints = 8;
 * @return {?proto.api.v1alpha1.classifier.ParseHints}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.getHints = function() {
  return /** @type{?proto.api.v1alpha1.classifier.ParseHints} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_classifier_entities_pb.ParseHints, 8));
};


/**
 * @param {?proto.api.v1alpha1.classifier.ParseHints|undefined} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} returns this
*/
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.setHints = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.clearHints = function() {
  return this.setHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints.prototype.hasHints = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional bytes raw_data = 3;
 * @return {string}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getRawData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes raw_data = 3;
 * This is a type-conversion wrapper around `getRawData()`
 * @return {string}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getRawData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRawData()));
};


/**
 * optional bytes raw_data = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRawData()`
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getRawData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRawData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.setRawData = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.clearRawData = function() {
  return jspb.Message.setOneofField(this, 3, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.hasRawData = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ReParseFile reparse_file = 4;
 * @return {?proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getReparseFile = function() {
  return /** @type{?proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile} */ (
    jspb.Message.getWrapperField(this, proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile, 4));
};


/**
 * @param {?proto.api.v1alpha1.classifier.ParseFileRequest.ReParseFile|undefined} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
*/
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.setReparseFile = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.clearReparseFile = function() {
  return this.setReparseFile(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.hasReparseFile = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ParseWithHints parse_with_hints = 6;
 * @return {?proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getParseWithHints = function() {
  return /** @type{?proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints} */ (
    jspb.Message.getWrapperField(this, proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints, 6));
};


/**
 * @param {?proto.api.v1alpha1.classifier.ParseFileRequest.ParseWithHints|undefined} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
*/
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.setParseWithHints = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.api.v1alpha1.classifier.ParseFileRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.clearParseWithHints = function() {
  return this.setParseWithHints(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.hasParseWithHints = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileRequest} returns this
 */
proto.api.v1alpha1.classifier.ParseFileRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ParseFileResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ParseFileResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplate: (f = msg.getFileTemplate()) && api_v1alpha1_classifier_entities_pb.FileTemplate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ParseFileResponse}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ParseFileResponse;
  return proto.api.v1alpha1.classifier.ParseFileResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ParseFileResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ParseFileResponse}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_v1alpha1_classifier_entities_pb.FileTemplate;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.FileTemplate.deserializeBinaryFromReader);
      msg.setFileTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ParseFileResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ParseFileResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ParseFileResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_v1alpha1_classifier_entities_pb.FileTemplate.serializeBinaryToWriter
    );
  }
};


/**
 * optional FileTemplate file_template = 1;
 * @return {?proto.api.v1alpha1.classifier.FileTemplate}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.getFileTemplate = function() {
  return /** @type{?proto.api.v1alpha1.classifier.FileTemplate} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_classifier_entities_pb.FileTemplate, 1));
};


/**
 * @param {?proto.api.v1alpha1.classifier.FileTemplate|undefined} value
 * @return {!proto.api.v1alpha1.classifier.ParseFileResponse} returns this
*/
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.setFileTemplate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.ParseFileResponse} returns this
 */
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.clearFileTemplate = function() {
  return this.setFileTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ParseFileResponse.prototype.hasFileTemplate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplate: (f = msg.getFileTemplate()) && api_v1alpha1_classifier_entities_pb.FileTemplate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.UpdateFileTemplateRequest;
  return proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_v1alpha1_classifier_entities_pb.FileTemplate;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.FileTemplate.deserializeBinaryFromReader);
      msg.setFileTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_v1alpha1_classifier_entities_pb.FileTemplate.serializeBinaryToWriter
    );
  }
};


/**
 * optional FileTemplate file_template = 1;
 * @return {?proto.api.v1alpha1.classifier.FileTemplate}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.getFileTemplate = function() {
  return /** @type{?proto.api.v1alpha1.classifier.FileTemplate} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_classifier_entities_pb.FileTemplate, 1));
};


/**
 * @param {?proto.api.v1alpha1.classifier.FileTemplate|undefined} value
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest} returns this
*/
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.setFileTemplate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateRequest} returns this
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.clearFileTemplate = function() {
  return this.setFileTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateRequest.prototype.hasFileTemplate = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.UpdateFileTemplateResponse;
  return proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.UpdateFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.UpdateFileTemplateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.UpdateFileTemplateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplate: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.DeleteFileTemplateRequest;
  return proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFileTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplate();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 file_template = 1;
 * @return {number}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.prototype.getFileTemplate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.classifier.DeleteFileTemplateRequest} returns this
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateRequest.prototype.setFileTemplate = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.DeleteFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.DeleteFileTemplateResponse;
  return proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.DeleteFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.DeleteFileTemplateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.DeleteFileTemplateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ListFileTemplatesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    prevId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    asc: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    pageSize: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ListFileTemplatesRequest;
  return proto.api.v1alpha1.classifier.ListFileTemplatesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPrevId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAsc(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ListFileTemplatesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrevId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getAsc();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int64 prev_id = 1;
 * @return {number}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.getPrevId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} returns this
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.setPrevId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool asc = 2;
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.getAsc = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} returns this
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.setAsc = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional int32 page_size = 3;
 * @return {number}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesRequest} returns this
 */
proto.api.v1alpha1.classifier.ListFileTemplatesRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.ListFileTemplatesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplatesList: jspb.Message.toObjectList(msg.getFileTemplatesList(),
    api_v1alpha1_classifier_entities_pb.FileTemplate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.ListFileTemplatesResponse;
  return proto.api.v1alpha1.classifier.ListFileTemplatesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_v1alpha1_classifier_entities_pb.FileTemplate;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.FileTemplate.deserializeBinaryFromReader);
      msg.addFileTemplates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.ListFileTemplatesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      api_v1alpha1_classifier_entities_pb.FileTemplate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated FileTemplate file_templates = 1;
 * @return {!Array<!proto.api.v1alpha1.classifier.FileTemplate>}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.getFileTemplatesList = function() {
  return /** @type{!Array<!proto.api.v1alpha1.classifier.FileTemplate>} */ (
    jspb.Message.getRepeatedWrapperField(this, api_v1alpha1_classifier_entities_pb.FileTemplate, 1));
};


/**
 * @param {!Array<!proto.api.v1alpha1.classifier.FileTemplate>} value
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse} returns this
*/
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.setFileTemplatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.v1alpha1.classifier.FileTemplate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.v1alpha1.classifier.FileTemplate}
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.addFileTemplates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.v1alpha1.classifier.FileTemplate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.v1alpha1.classifier.ListFileTemplatesResponse} returns this
 */
proto.api.v1alpha1.classifier.ListFileTemplatesResponse.prototype.clearFileTemplatesList = function() {
  return this.setFileTemplatesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.GetFileTemplateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplateId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.GetFileTemplateRequest;
  return proto.api.v1alpha1.classifier.GetFileTemplateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateRequest}
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFileTemplateId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.GetFileTemplateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplateId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 file_template_id = 1;
 * @return {number}
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.prototype.getFileTemplateId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateRequest} returns this
 */
proto.api.v1alpha1.classifier.GetFileTemplateRequest.prototype.setFileTemplateId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.classifier.GetFileTemplateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileTemplate: (f = msg.getFileTemplate()) && api_v1alpha1_classifier_entities_pb.FileTemplate.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.classifier.GetFileTemplateResponse;
  return proto.api.v1alpha1.classifier.GetFileTemplateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateResponse}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_v1alpha1_classifier_entities_pb.FileTemplate;
      reader.readMessage(value,api_v1alpha1_classifier_entities_pb.FileTemplate.deserializeBinaryFromReader);
      msg.setFileTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.classifier.GetFileTemplateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.classifier.GetFileTemplateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileTemplate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_v1alpha1_classifier_entities_pb.FileTemplate.serializeBinaryToWriter
    );
  }
};


/**
 * optional FileTemplate file_template = 1;
 * @return {?proto.api.v1alpha1.classifier.FileTemplate}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.getFileTemplate = function() {
  return /** @type{?proto.api.v1alpha1.classifier.FileTemplate} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_classifier_entities_pb.FileTemplate, 1));
};


/**
 * @param {?proto.api.v1alpha1.classifier.FileTemplate|undefined} value
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateResponse} returns this
*/
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.setFileTemplate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.classifier.GetFileTemplateResponse} returns this
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.clearFileTemplate = function() {
  return this.setFileTemplate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.classifier.GetFileTemplateResponse.prototype.hasFileTemplate = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.api.v1alpha1.classifier);
