// source: api/v1alpha1/vanalytics/flag_transcript_filter.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var proto = {};

var api_v1alpha1_vanalytics_filter_snapshot_pb = require('../../../api/v1alpha1/vanalytics/filter_snapshot_pb.js');
goog.object.extend(proto, api_v1alpha1_vanalytics_filter_snapshot_pb);
var api_v1alpha1_vanalytics_flag_snapshot_pb = require('../../../api/v1alpha1/vanalytics/flag_snapshot_pb.js');
goog.object.extend(proto, api_v1alpha1_vanalytics_flag_snapshot_pb);
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
goog.object.extend(proto, google_protobuf_field_mask_pb);
goog.exportSymbol('api.v1alpha1.vanalytics.FlagTranscriptFilter', null, proto);
goog.exportSymbol('api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest', null, proto);
goog.exportSymbol('api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse', null, proto);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.displayName = 'proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.repeatedFields_, null);
};
goog.inherits(proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.displayName = 'proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.v1alpha1.vanalytics.FlagTranscriptFilter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.displayName = 'proto.api.v1alpha1.vanalytics.FlagTranscriptFilter';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
transcriptSid: jspb.Message.getFieldWithDefault(msg, 2, 0),
flagSnapshotMask: (f = msg.getFlagSnapshotMask()) && google_protobuf_field_mask_pb.FieldMask.toObject(includeInstance, f),
filterSnapshotMask: (f = msg.getFilterSnapshotMask()) && google_protobuf_field_mask_pb.FieldMask.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest;
  return proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTranscriptSid(value);
      break;
    case 3:
      var value = new google_protobuf_field_mask_pb.FieldMask;
      reader.readMessage(value,google_protobuf_field_mask_pb.FieldMask.deserializeBinaryFromReader);
      msg.setFlagSnapshotMask(value);
      break;
    case 4:
      var value = new google_protobuf_field_mask_pb.FieldMask;
      reader.readMessage(value,google_protobuf_field_mask_pb.FieldMask.deserializeBinaryFromReader);
      msg.setFilterSnapshotMask(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTranscriptSid();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getFlagSnapshotMask();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_field_mask_pb.FieldMask.serializeBinaryToWriter
    );
  }
  f = message.getFilterSnapshotMask();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_field_mask_pb.FieldMask.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 transcript_sid = 2;
 * @return {number}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.getTranscriptSid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} returns this
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.setTranscriptSid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional google.protobuf.FieldMask flag_snapshot_mask = 3;
 * @return {?proto.google.protobuf.FieldMask}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.getFlagSnapshotMask = function() {
  return /** @type{?proto.google.protobuf.FieldMask} */ (
    jspb.Message.getWrapperField(this, google_protobuf_field_mask_pb.FieldMask, 3));
};


/**
 * @param {?proto.google.protobuf.FieldMask|undefined} value
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} returns this
*/
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.setFlagSnapshotMask = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} returns this
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.clearFlagSnapshotMask = function() {
  return this.setFlagSnapshotMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.hasFlagSnapshotMask = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.FieldMask filter_snapshot_mask = 4;
 * @return {?proto.google.protobuf.FieldMask}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.getFilterSnapshotMask = function() {
  return /** @type{?proto.google.protobuf.FieldMask} */ (
    jspb.Message.getWrapperField(this, google_protobuf_field_mask_pb.FieldMask, 4));
};


/**
 * @param {?proto.google.protobuf.FieldMask|undefined} value
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} returns this
*/
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.setFilterSnapshotMask = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest} returns this
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.clearFilterSnapshotMask = function() {
  return this.setFilterSnapshotMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersRequest.prototype.hasFilterSnapshotMask = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
flagTranscriptFiltersList: jspb.Message.toObjectList(msg.getFlagTranscriptFiltersList(),
    proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse;
  return proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.v1alpha1.vanalytics.FlagTranscriptFilter;
      reader.readMessage(value,proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.deserializeBinaryFromReader);
      msg.addFlagTranscriptFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlagTranscriptFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.serializeBinaryToWriter
    );
  }
};


/**
 * repeated FlagTranscriptFilter flag_transcript_filters = 1;
 * @return {!Array<!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter>}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.getFlagTranscriptFiltersList = function() {
  return /** @type{!Array<!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.v1alpha1.vanalytics.FlagTranscriptFilter, 1));
};


/**
 * @param {!Array<!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter>} value
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse} returns this
*/
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.setFlagTranscriptFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter}
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.addFlagTranscriptFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.v1alpha1.vanalytics.FlagTranscriptFilter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse} returns this
 */
proto.api.v1alpha1.vanalytics.ListFlagTranscriptFiltersResponse.prototype.clearFlagTranscriptFiltersList = function() {
  return this.setFlagTranscriptFiltersList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.toObject = function(opt_includeInstance) {
  return proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.toObject = function(includeInstance, msg) {
  var f, obj = {
flagSnapshot: (f = msg.getFlagSnapshot()) && api_v1alpha1_vanalytics_flag_snapshot_pb.FlagSnapshot.toObject(includeInstance, f),
filterSnapshot: (f = msg.getFilterSnapshot()) && api_v1alpha1_vanalytics_filter_snapshot_pb.FilterSnapshot.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.v1alpha1.vanalytics.FlagTranscriptFilter;
  return proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_v1alpha1_vanalytics_flag_snapshot_pb.FlagSnapshot;
      reader.readMessage(value,api_v1alpha1_vanalytics_flag_snapshot_pb.FlagSnapshot.deserializeBinaryFromReader);
      msg.setFlagSnapshot(value);
      break;
    case 2:
      var value = new api_v1alpha1_vanalytics_filter_snapshot_pb.FilterSnapshot;
      reader.readMessage(value,api_v1alpha1_vanalytics_filter_snapshot_pb.FilterSnapshot.deserializeBinaryFromReader);
      msg.setFilterSnapshot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFlagSnapshot();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_v1alpha1_vanalytics_flag_snapshot_pb.FlagSnapshot.serializeBinaryToWriter
    );
  }
  f = message.getFilterSnapshot();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      api_v1alpha1_vanalytics_filter_snapshot_pb.FilterSnapshot.serializeBinaryToWriter
    );
  }
};


/**
 * optional FlagSnapshot flag_snapshot = 1;
 * @return {?proto.api.v1alpha1.vanalytics.FlagSnapshot}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.getFlagSnapshot = function() {
  return /** @type{?proto.api.v1alpha1.vanalytics.FlagSnapshot} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_vanalytics_flag_snapshot_pb.FlagSnapshot, 1));
};


/**
 * @param {?proto.api.v1alpha1.vanalytics.FlagSnapshot|undefined} value
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} returns this
*/
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.setFlagSnapshot = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} returns this
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.clearFlagSnapshot = function() {
  return this.setFlagSnapshot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.hasFlagSnapshot = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional FilterSnapshot filter_snapshot = 2;
 * @return {?proto.api.v1alpha1.vanalytics.FilterSnapshot}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.getFilterSnapshot = function() {
  return /** @type{?proto.api.v1alpha1.vanalytics.FilterSnapshot} */ (
    jspb.Message.getWrapperField(this, api_v1alpha1_vanalytics_filter_snapshot_pb.FilterSnapshot, 2));
};


/**
 * @param {?proto.api.v1alpha1.vanalytics.FilterSnapshot|undefined} value
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} returns this
*/
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.setFilterSnapshot = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.v1alpha1.vanalytics.FlagTranscriptFilter} returns this
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.clearFilterSnapshot = function() {
  return this.setFilterSnapshot(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.v1alpha1.vanalytics.FlagTranscriptFilter.prototype.hasFilterSnapshot = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
