// package: api.commons
// file: api/commons/inbound.proto

import * as jspb from "google-protobuf";

export interface InboundGroupStatusMap {
  IBG_UNKNOWN: 0;
  IBG_PREPARE: 5000;
  IBG_SCHEDULED: 5100;
  IBG_RUNNING: 5200;
  IBG_PAUSED: 5210;
  IBG_COMPLETED: 5300;
  IBG_CANCELLED_TIMEOUT: 5310;
  IBG_CANCELLED_USER: 5320;
  IBG_CANCELLED_ADMIN: 5330;
  IBG_SUMMED_COMPLETED: 5400;
  IBG_SUMMED_CANCELLED_TIMEOUT: 5410;
  IBG_SUMMED_CANCELLED_USER: 5420;
  IBG_SUMMED_CANCELLED_ADMIN: 5430;
  IBG_ACCOUNTINGEXPORT_COMPLETED: 5500;
  IBG_ACCOUNTINGEXPORT_CANCELLED_TIMEOUT: 5510;
  IBG_ACCOUNTINGEXPORT_CANCELLED_USER: 5520;
  IBG_ACCOUNTINGEXPORT_CANCELLED_ADMIN: 5530;
}

export const InboundGroupStatus: InboundGroupStatusMap;

