// package: api.commons
// file: api/commons/manual.proto

import * as jspb from "google-protobuf";

export interface ManualDialGroupStatusMap {
  MDG_UNKNOWN: 0;
  MDG_PREPARE: 6000;
  MDG_SCHEDULED: 6100;
  MDG_RUNNING: 6200;
  MDG_COMPLETED: 6300;
  MDG_CANCELLED_TIMEOUT: 6310;
  MDG_CANCELLED_USER: 6320;
  MDG_CANCELLED_ADMIN: 6330;
  MDG_SUMMED_COMPLETED: 6400;
  MDG_SUMMED_CANCELLED_TIMEOUT: 6410;
  MDG_SUMMED_CANCELLED_USER: 6420;
  MDG_SUMMED_CANCELLED_ADMIN: 6430;
  MDG_ACCOUNTINGEXPORT_COMPLETED: 6500;
  MDG_ACCOUNTINGEXPORT_CANCELLED_TIMEOUT: 6510;
  MDG_ACCOUNTINGEXPORT_CANCELLED_USER: 6520;
  MDG_ACCOUNTINGEXPORT_CANCELLED_ADMIN: 6530;
}

export const ManualDialGroupStatus: ManualDialGroupStatusMap;

