// package: api.commons
// file: api/commons/task_group.proto

import * as jspb from "google-protobuf";

export interface TaskGroupStatusMap {
  TG_UNKNOWN: 0;
  TG_PREPARE: 1000;
  TG_SCHEDULED: 1100;
  TG_SCHEDULED_LINKING: 1110;
  TG_SCHEDULED_PAUSED: 1120;
  TG_RUNNING: 1200;
  TG_PAUSED: 1210;
  TG_WAITING: 1220;
  TG_COMPLETED: 1300;
  TG_CANCELLED_TIMEOUT: 1310;
  TG_CANCELLED_USER: 1320;
  TG_CANCELLED_ADMIN: 1330;
  TG_SUMMED_COMPLETED: 1400;
  TG_SUMMED_CANCELLED_TIMEOUT: 1410;
  TG_SUMMED_CANCELLED_USER: 1420;
  TG_SUMMED_CANCELLED_ADMIN: 1430;
  TG_ACCOUNTINGEXPORT_COMPLETED: 1500;
  TG_ACCOUNTINGEXPORT_CANCELLED_TIMEOUT: 1510;
  TG_ACCOUNTINGEXPORT_CANCELLED_USER: 1520;
  TG_ACCOUNTINGEXPORT_CANCELLED_ADMIN: 1530;
}

export const TaskGroupStatus: TaskGroupStatusMap;

