// source: services/billing/entities/v1alpha2/invoice.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var localGlobalThis = require("../../../../global.js");
var proto = localGlobalThis.proto;
var goog = jspb;
var global = localGlobalThis || 
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_type_decimal_pb = require('../../../../google/type/decimal_pb.js');
goog.object.extend(proto, google_type_decimal_pb);
goog.exportSymbol('proto.services.billing.entities.v1alpha2.Invoice', null, global);
goog.exportSymbol('proto.services.billing.entities.v1alpha2.InvoiceItem', null, global);
goog.exportSymbol('proto.services.billing.entities.v1alpha2.InvoiceItemColumn', null, global);
goog.exportSymbol('proto.services.billing.entities.v1alpha2.Product', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.billing.entities.v1alpha2.Invoice = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.services.billing.entities.v1alpha2.Invoice.repeatedFields_, null);
};
goog.inherits(proto.services.billing.entities.v1alpha2.Invoice, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.billing.entities.v1alpha2.Invoice.displayName = 'proto.services.billing.entities.v1alpha2.Invoice';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.billing.entities.v1alpha2.InvoiceItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.services.billing.entities.v1alpha2.InvoiceItem.repeatedFields_, null);
};
goog.inherits(proto.services.billing.entities.v1alpha2.InvoiceItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.billing.entities.v1alpha2.InvoiceItem.displayName = 'proto.services.billing.entities.v1alpha2.InvoiceItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.billing.entities.v1alpha2.InvoiceItemColumn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.billing.entities.v1alpha2.InvoiceItemColumn.displayName = 'proto.services.billing.entities.v1alpha2.InvoiceItemColumn';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.services.billing.entities.v1alpha2.Invoice.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.toObject = function(opt_includeInstance) {
  return proto.services.billing.entities.v1alpha2.Invoice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.billing.entities.v1alpha2.Invoice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.Invoice.toObject = function(includeInstance, msg) {
  var f, obj = {
billingCycle: jspb.Message.getFieldWithDefault(msg, 1, ""),
createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.services.billing.entities.v1alpha2.InvoiceItem.toObject, includeInstance),
downloadUrl: (f = msg.getDownloadUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.billing.entities.v1alpha2.Invoice}
 */
proto.services.billing.entities.v1alpha2.Invoice.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.billing.entities.v1alpha2.Invoice;
  return proto.services.billing.entities.v1alpha2.Invoice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.billing.entities.v1alpha2.Invoice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.billing.entities.v1alpha2.Invoice}
 */
proto.services.billing.entities.v1alpha2.Invoice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBillingCycle(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 3:
      var value = new proto.services.billing.entities.v1alpha2.InvoiceItem;
      reader.readMessage(value,proto.services.billing.entities.v1alpha2.InvoiceItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setDownloadUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.billing.entities.v1alpha2.Invoice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.billing.entities.v1alpha2.Invoice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.Invoice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBillingCycle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.services.billing.entities.v1alpha2.InvoiceItem.serializeBinaryToWriter
    );
  }
  f = message.getDownloadUrl();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional string billing_cycle = 1;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.getBillingCycle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.setBillingCycle = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp create_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
*/
proto.services.billing.entities.v1alpha2.Invoice.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated InvoiceItem items = 3;
 * @return {!Array<!proto.services.billing.entities.v1alpha2.InvoiceItem>}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.services.billing.entities.v1alpha2.InvoiceItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.services.billing.entities.v1alpha2.InvoiceItem, 3));
};


/**
 * @param {!Array<!proto.services.billing.entities.v1alpha2.InvoiceItem>} value
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
*/
proto.services.billing.entities.v1alpha2.Invoice.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.services.billing.entities.v1alpha2.InvoiceItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


/**
 * optional google.protobuf.StringValue download_url = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.getDownloadUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
*/
proto.services.billing.entities.v1alpha2.Invoice.prototype.setDownloadUrl = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.billing.entities.v1alpha2.Invoice} returns this
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.clearDownloadUrl = function() {
  return this.setDownloadUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.billing.entities.v1alpha2.Invoice.prototype.hasDownloadUrl = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.toObject = function(opt_includeInstance) {
  return proto.services.billing.entities.v1alpha2.InvoiceItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.toObject = function(includeInstance, msg) {
  var f, obj = {
clientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
product: jspb.Message.getFieldWithDefault(msg, 2, 0),
description: jspb.Message.getFieldWithDefault(msg, 3, ""),
date: (f = msg.getDate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
price: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
columnsList: jspb.Message.toObjectList(msg.getColumnsList(),
    proto.services.billing.entities.v1alpha2.InvoiceItemColumn.toObject, includeInstance),
ratedAmount: (f = msg.getRatedAmount()) && google_type_decimal_pb.Decimal.toObject(includeInstance, f),
productId: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.billing.entities.v1alpha2.InvoiceItem;
  return proto.services.billing.entities.v1alpha2.InvoiceItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setClientId(value);
      break;
    case 2:
      var value = /** @type {!proto.services.billing.entities.v1alpha2.Product} */ (reader.readEnum());
      msg.setProduct(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 6:
      var value = new proto.services.billing.entities.v1alpha2.InvoiceItemColumn;
      reader.readMessage(value,proto.services.billing.entities.v1alpha2.InvoiceItemColumn.deserializeBinaryFromReader);
      msg.addColumns(value);
      break;
    case 7:
      var value = new google_type_decimal_pb.Decimal;
      reader.readMessage(value,google_type_decimal_pb.Decimal.deserializeBinaryFromReader);
      msg.setRatedAmount(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.billing.entities.v1alpha2.InvoiceItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getClientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProduct();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDate();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getColumnsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.services.billing.entities.v1alpha2.InvoiceItemColumn.serializeBinaryToWriter
    );
  }
  f = message.getRatedAmount();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_type_decimal_pb.Decimal.serializeBinaryToWriter
    );
  }
  f = message.getProductId();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional string client_id = 1;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getClientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setClientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Product product = 2;
 * @return {!proto.services.billing.entities.v1alpha2.Product}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getProduct = function() {
  return /** @type {!proto.services.billing.entities.v1alpha2.Product} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.services.billing.entities.v1alpha2.Product} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setProduct = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp date = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getDate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
*/
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setDate = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.clearDate = function() {
  return this.setDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.hasDate = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double price = 5;
 * @return {number}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * repeated InvoiceItemColumn columns = 6;
 * @return {!Array<!proto.services.billing.entities.v1alpha2.InvoiceItemColumn>}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getColumnsList = function() {
  return /** @type{!Array<!proto.services.billing.entities.v1alpha2.InvoiceItemColumn>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.services.billing.entities.v1alpha2.InvoiceItemColumn, 6));
};


/**
 * @param {!Array<!proto.services.billing.entities.v1alpha2.InvoiceItemColumn>} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
*/
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setColumnsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn=} opt_value
 * @param {number=} opt_index
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.addColumns = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.services.billing.entities.v1alpha2.InvoiceItemColumn, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.clearColumnsList = function() {
  return this.setColumnsList([]);
};


/**
 * optional google.type.Decimal rated_amount = 7;
 * @return {?proto.google.type.Decimal}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getRatedAmount = function() {
  return /** @type{?proto.google.type.Decimal} */ (
    jspb.Message.getWrapperField(this, google_type_decimal_pb.Decimal, 7));
};


/**
 * @param {?proto.google.type.Decimal|undefined} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
*/
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setRatedAmount = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.clearRatedAmount = function() {
  return this.setRatedAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.hasRatedAmount = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string product_id = 8;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.getProductId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItem} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItem.prototype.setProductId = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.toObject = function(opt_includeInstance) {
  return proto.services.billing.entities.v1alpha2.InvoiceItemColumn.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
value: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.billing.entities.v1alpha2.InvoiceItemColumn;
  return proto.services.billing.entities.v1alpha2.InvoiceItemColumn.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.billing.entities.v1alpha2.InvoiceItemColumn.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string value = 2;
 * @return {string}
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.billing.entities.v1alpha2.InvoiceItemColumn} returns this
 */
proto.services.billing.entities.v1alpha2.InvoiceItemColumn.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.services.billing.entities.v1alpha2.Product = {
  PRODUCT_UNSPECIFIED: 0,
  PRODUCT_OMNI: 200,
  PRODUCT_OMNI_SEATS: 201,
  PRODUCT_OMNI_CHAT_SENT: 202,
  PRODUCT_OMNI_CHAT_RECEIVED: 203,
  PRODUCT_OMNI_EMAILS_SENT: 204,
  PRODUCT_OMNI_EMAILS_RECEIVED: 205,
  PRODUCT_OMNI_SMS_SENT: 206,
  PRODUCT_OMNI_SMS_RECEIVED: 207,
  PRODUCT_COMPLIANCE: 300
};

goog.object.extend(exports, proto.services.billing.entities.v1alpha2);
