// source: services/callmonitor/v1alpha1/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var localGlobalThis = require("../../../global.js");
var proto = localGlobalThis.proto;
var goog = jspb;
var global = localGlobalThis || 
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var annotations_authz_pb = require('../../../annotations/authz_pb.js');
goog.object.extend(proto, annotations_authz_pb);
var api_commons_callmonitor_pb = require('../../../api/commons/callmonitor_pb.js');
goog.object.extend(proto, api_commons_callmonitor_pb);
var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.services.callmonitor.v1alpha1.GetStatsRequest', null, global);
goog.exportSymbol('proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter', null, global);
goog.exportSymbol('proto.services.callmonitor.v1alpha1.GetStatsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.callmonitor.v1alpha1.GetStatsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.callmonitor.v1alpha1.GetStatsRequest.displayName = 'proto.services.callmonitor.v1alpha1.GetStatsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.displayName = 'proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.services.callmonitor.v1alpha1.GetStatsResponse.repeatedFields_, null);
};
goog.inherits(proto.services.callmonitor.v1alpha1.GetStatsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.services.callmonitor.v1alpha1.GetStatsResponse.displayName = 'proto.services.callmonitor.v1alpha1.GetStatsResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.services.callmonitor.v1alpha1.GetStatsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
orgId: jspb.Message.getFieldWithDefault(msg, 1, ""),
startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
filter: (f = msg.getFilter()) && proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.callmonitor.v1alpha1.GetStatsRequest;
  return proto.services.callmonitor.v1alpha1.GetStatsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 4:
      var value = new proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter;
      reader.readMessage(value,proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.callmonitor.v1alpha1.GetStatsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrgId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
status: jspb.Message.getFieldWithDefault(msg, 1, 0),
campaignId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter;
  return proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.api.commons.MonitorStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCampaignId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCampaignId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional api.commons.MonitorStatus status = 1;
 * @return {!proto.api.commons.MonitorStatus}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.getStatus = function() {
  return /** @type {!proto.api.commons.MonitorStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.api.commons.MonitorStatus} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string campaign_id = 3;
 * @return {string}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.getCampaignId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter.prototype.setCampaignId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string org_id = 1;
 * @return {string}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.getOrgId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.setOrgId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp start_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
*/
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
*/
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Filter filter = 4;
 * @return {?proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.getFilter = function() {
  return /** @type{?proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter} */ (
    jspb.Message.getWrapperField(this, proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter, 4));
};


/**
 * @param {?proto.services.callmonitor.v1alpha1.GetStatsRequest.Filter|undefined} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
*/
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsRequest} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.services.callmonitor.v1alpha1.GetStatsRequest.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.services.callmonitor.v1alpha1.GetStatsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
statsList: jspb.Message.toObjectList(msg.getStatsList(),
    api_commons_callmonitor_pb.CallStats.toObject, includeInstance),
totalNumCalls: jspb.Message.getFieldWithDefault(msg, 2, 0),
totalNumSuccessful: jspb.Message.getFieldWithDefault(msg, 3, 0),
totalNumFailed: jspb.Message.getFieldWithDefault(msg, 4, 0),
avgMonitorDurationMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
totalNumMonitoring: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.services.callmonitor.v1alpha1.GetStatsResponse;
  return proto.services.callmonitor.v1alpha1.GetStatsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_commons_callmonitor_pb.CallStats;
      reader.readMessage(value,api_commons_callmonitor_pb.CallStats.deserializeBinaryFromReader);
      msg.addStats(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalNumCalls(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalNumSuccessful(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalNumFailed(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAvgMonitorDurationMs(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalNumMonitoring(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.services.callmonitor.v1alpha1.GetStatsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.services.callmonitor.v1alpha1.GetStatsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      api_commons_callmonitor_pb.CallStats.serializeBinaryToWriter
    );
  }
  f = message.getTotalNumCalls();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTotalNumSuccessful();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getTotalNumFailed();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getAvgMonitorDurationMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getTotalNumMonitoring();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * repeated api.commons.CallStats stats = 1;
 * @return {!Array<!proto.api.commons.CallStats>}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getStatsList = function() {
  return /** @type{!Array<!proto.api.commons.CallStats>} */ (
    jspb.Message.getRepeatedWrapperField(this, api_commons_callmonitor_pb.CallStats, 1));
};


/**
 * @param {!Array<!proto.api.commons.CallStats>} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
*/
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setStatsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.commons.CallStats=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.commons.CallStats}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.addStats = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.commons.CallStats, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.clearStatsList = function() {
  return this.setStatsList([]);
};


/**
 * optional int32 total_num_calls = 2;
 * @return {number}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getTotalNumCalls = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setTotalNumCalls = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 total_num_successful = 3;
 * @return {number}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getTotalNumSuccessful = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setTotalNumSuccessful = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 total_num_failed = 4;
 * @return {number}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getTotalNumFailed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setTotalNumFailed = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 avg_monitor_duration_ms = 5;
 * @return {number}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getAvgMonitorDurationMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setAvgMonitorDurationMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 total_num_monitoring = 6;
 * @return {number}
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.getTotalNumMonitoring = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.services.callmonitor.v1alpha1.GetStatsResponse} returns this
 */
proto.services.callmonitor.v1alpha1.GetStatsResponse.prototype.setTotalNumMonitoring = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


goog.object.extend(exports, proto.services.callmonitor.v1alpha1);
